[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "buildozer>=1.5.0",
    "ccxt>=4.5.11",
    "gradio>=5.49.1",
    "kivy>=2.3.1",
    "pandas>=2.3.3",
    "python-dotenv>=1.1.1",
]
